name: Pipeline
on: [push, pull_request]
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Para obtener todo el historial de commits
      - name: Preserve timestamps
        run: |
          git ls-files -z | while read -d '' path; do
            touch -d "$(git log -1 --format="@%ct" "$path")" "$path"
          done
